# Generated by Django 2.2.12 on 2020-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('guest', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='soundcloud',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
