# Generated by Django 2.2.12 on 2020-06-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpcomingShows',
            new_name='UpcomingShow',
        ),
    ]
