# Generated by Django 2.2.12 on 2020-06-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200604_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingshow',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=9),
            preserve_default=False,
        ),
    ]
