# Generated by Django 2.2.12 on 2020-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_upcomingshow_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingshow',
            name='time',
            field=models.CharField(default='1:00', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingshow',
            name='date',
            field=models.DateField(),
        ),
    ]
