# Generated by Django 2.2.12 on 2020-06-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bandcamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandcamp',
            old_name='embed_url',
            new_name='iframe_a_href',
        ),
        migrations.AddField(
            model_name='bandcamp',
            name='iframe_a_text',
            field=models.CharField(default='a', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandcamp',
            name='iframe_src',
            field=models.CharField(default='a', max_length=10000),
            preserve_default=False,
        ),
    ]
