# Generated by Django 2.2.12 on 2020-06-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200604_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingshow',
            name='city',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingshow',
            name='venue',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
