# Generated by Django 2.2.12 on 2020-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200605_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingshow',
            name='link_to_tickets',
            field=models.CharField(default='A', max_length=500),
            preserve_default=False,
        ),
    ]
