# Generated by Django 2.2.12 on 2020-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(default='post'),
            preserve_default=False,
        ),
    ]
